### Index
GET /api/settings HTTP/1.1
Host: {{ host }}

### Update
PATCH /api/settings HTTP/1.1
Host: {{ host }}
Authorization: {{ token }}

{
    "site_title": "Offer Title Updated",
    "site_about": ["Site about update"],
    "address": "Updated Address",
    "social": [
        {
            "key": "tel",
            "label": "Telefono",
            "icon": "ion-phone",
            "link":"tel:53375180"
        },
        {
            "key": "email",
            "label": "Email",
            "icon": "icon-email",
            "link":"mailto:acq95@nauta.cu"
        }
    ]
}
